### ISSUE TITLE
cannot import name version

### ISSUE THREAD

**Issue by Nick-Alam** [tosher/Mediawiker#101]
I'm using ```ST3 on linux, and my ST3 version is 3126```.
Encouter some import issues when I am trying to install the plugin: 
```python
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/user/.config/sublime-text-3/Packages/Mediawiker/mediawiker.py", line 21, in <module>
    from .mwcommands import mw_utils as mw
  File "/home/user/.config/sublime-text-3/Packages/Mediawiker/mwcommands/__init__.py", line 30, in <module>
    from .mw_configurator import MediawikerConfiguratorCommand
  File "/home/user/.config/sublime-text-3/Packages/Mediawiker/mwcommands/mw_configurator.py", line 11, in <module>
    import mdpopups
  File "/home/user/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 16, in <module>
    from . import version as ver
ImportError: cannot import name version
```
I have tried git clone sublime-markdown-popups from github into folder ```/home/user/.config/sublime-text-3/Packages/```, but  no luck. 
I don't think there is some python language error here in the line ```from . import version as ver```, could you give a hand on this?

**Comment by tosher** [comment]
[Package control](https://packagecontrol.io) is [required](https://github.com/tosher/Mediawiker#package-control) to install the plugin and all dependencies for it.

**Comment by Nick-Alam** [comment]
Hi tosher,

I actually installed Mediawiker via ST package control, all the dependencied have been resolved by still get that err

**Comment by Nick-Alam** [comment]
Hi tosher,
I actually installed Mediawiker via ST package control, all the dependencies have been resolved but still get that err.

**Comment by tosher** [comment]
And after restarting Sublime, the same error?

**Comment by tosher** [comment]
Mdpopups was removed from plugin's dependencies, please check the new version.
