### ISSUE TITLE
"readapidenied, You need read permission to use this module" error after some time

### ISSUE THREAD

**Issue by rabin-io** [tosher/Mediawiker#104]
I can't pint point the problem, but some times when I come to save a wiki page which was opened in ST3 for some time, I don't get the prompt for the commit message. And when I look in the console i see the message
```
Traceback (most recent call last):
  File "/opt/sublime_text_3_build_3126/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mediawiker.py", line 99, in run
    self.page = mw.get_page(self.sitecon, self.title)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwcommands/mw_utils.py", line 167, in get_page
    return site.Pages[title]
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/listing.py", line 210, in __getitem__
    return self.get(name, None)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/listing.py", line 228, in get
    return self.page_class(self.site, name, info)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/page.py", line 36, in __init__
    inprop='protection', *extra_props)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 273, in api
    if self.handle_api_result(info, sleeper=sleeper):
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 296, in handle_api_result
    info['error']['info'], info['error']['*'])
Mediawiker.mwclient.errors.APIError: ('readapidenied', 'You need read permission to use this module', 'See https://wiki/api.php for API usage')
```

But when restarting ST3, the saving and page opening would work again.

running ST3 build 3126.

**Comment by tosher** [comment]
Thanks, maybe i know the cause.. will check.

**Comment by rabin-io** [comment]
Hi, did you happen to check about this problem?

**Comment by tosher** [comment]
Sorry for silence, problem in progress.. needs some time for research..

**Comment by rabin-io** [comment]
Thanks. 
Please let me know if you need any more info about my setup.

**Comment by tosher** [comment]
Is the problem actual with latest versions? In many situations with lost connection properties, the plugin tries to make new connection.
