### ISSUE TITLE
can't get v.3.3.0 to work: AttributeError: 'NoneType' object has no attribute 'get_view_setting'

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#112]
ST3 3126. Ever since the move to 3.3.0 in package control, I haven't been able to get mediawiker to work. I just completely removed and reinstalled mediawiker and anything I do shows the following in the console. I don't think it can even load the plugin.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_events.py", line 51, in on_activated
    current_syntax = mw.props.get_view_setting(view, 'syntax', plugin=False)
AttributeError: 'NoneType' object has no attribute 'get_view_setting'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_events.py", line 71, in on_activated_async
    if mw.props.get_view_setting(view, 'is_here'):
AttributeError: 'NoneType' object has no attribute 'get_view_setting'
```

**Comment by reagle** [comment]
Restart ST3 (on Mac Capitan) and looking at console shows this upon start:

```
...
plugins loaded
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 73, in plugin_loaded
    props = mwprops.MediawikerProperties()
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_properties.py", line 134, in __init__
    self.reload_settings()
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_properties.py", line 157, in reload_settings
    self.settings_user = sublime.decode_value(sublime.load_resource(from_package('Mediawiker.sublime-settings', name='User')))
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mediawiker.py", line 27, in plugin_loaded
    mw.plugin_loaded()
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 73, in plugin_loaded
    props = mwprops.MediawikerProperties()
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_properties.py", line 134, in __init__
    self.reload_settings()
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_properties.py", line 157, in reload_settings
    self.settings_user = sublime.decode_value(sublime.load_resource(from_package('Mediawiker.sublime-settings', name='User')))
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_events.py", line 51, in on_activated
    current_syntax = mw.props.get_view_setting(view, 'syntax', plugin=False)
AttributeError: 'NoneType' object has no attribute 'get_view_setting'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_events.py", line 51, in on_activated
    current_syntax = mw.props.get_view_setting(view, 'syntax', plugin=False)
AttributeError: 'NoneType' object has no attribute 'get_view_setting'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_events.py", line 71, in on_activated_async
    if mw.props.get_view_setting(view, 'is_here'):
AttributeError: 'NoneType' object has no attribute 'get_view_setting'
```

**Comment by reagle** [comment]
I'm not sure why it is not finding those resources.

```
wor:~$ dir '/Applications/Sublime Text.app/Contents/MacOS/'
total 24188
drwxr-xr-x 51 reagle staff     1734 2016-09-23 06:12  Packages/
-rwxr-xr-x  1 reagle staff 12655744 2016-09-23 06:13 'Sublime Text'*
-rw-r--r--  1 reagle staff    30118 2016-09-23 06:12  changelog.txt
-rwxr-xr-x  1 reagle staff   204752 2016-09-23 06:12  crash_reporter*
-rwxr-xr-x  1 reagle staff  9126736 2016-09-23 06:13  plugin_host*
-rw-r--r--  1 reagle staff  2624408 2016-09-23 06:12  python3.3.zip
-rw-r--r--  1 reagle staff    37137 2016-09-23 06:12  sublime.py
-rw-r--r--  1 reagle staff    28578 2016-09-23 06:12  sublime_plugin.py
-rwxr-xr-x  1 reagle staff    48048 2016-09-23 06:13  update_installer*
```

**Comment by reagle** [comment]
Hrmm... maybe the above error is because I didn't set up my configuration after I nuked the mediawiker install. Feel free to close, but I wonder if anyone else had difficulty with the 3.3.0 update?

**Comment by tosher** [comment]
Thanks, i'll check this. 
After creating of user settings, plugin works?

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.3.1

**Comment by reagle** [comment]
Yes it dad; and thank you.
