### ISSUE TITLE
Cookie auth problem

### ISSUE THREAD

**Issue by nigobo** [tosher/Mediawiker#119]
Hi!

I am a frequent user of the MediaWiker plugin and it's awesome. We recently introduced SAML to our Wiki and I can't login directly to the Wiki anymore. I have tried to use my FireFox cookie but I get an error message.

### My Config

- `companyname.se` is really something else. :)

I have made sure that the `pagepath` and `path` are correct.

```
{
			"authorization_type": "cookies",
			"cookies_browser": "firefox",
			"host": "wiki.companyname.se",
			"https": true,
			"pagepath": "/index.php/",
			"path": "/",
			"use_http_auth": false
}
```

### Error message

```
'''Site configuration is changed, setup new connection to "CompanyName".. '''
Connecting to https://wiki.companyname.se ..  failed: Did not get a valid JSON response from the server. Check that you used the correct hostname. If you did, the server might be wrongly configured or experiencing temporary problems.
ConnectionFailed exception for get_page: No valid connection available
```

### Console log

```
Traceback (most recent call last):
  File "/Users/nigobo/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 952, in on_done
    set_timeout_async(self.callback(title), 0)
  File "/Users/nigobo/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mediawiker.py", line 79, in page_open
    if mw.api.page_can_edit(page):
  File "/Users/nigobo/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 500, in page_can_edit
    return page.can('edit')
AttributeError: 'NoneType' object has no attribute 'can'
```

What am I doing wrong? Any pointers?

**Comment by tosher** [comment]
Did it work before SAML was introduced (with just login/password or cookies)?

Do you use some Mediawiki extension for SAML or not? If yes, please, tell me it's name.

Extension example: 
https://www.mediawiki.org/wiki/Extension:SimpleSamlAuth

**Comment by nigobo** [comment]
I have used login/password for a few years without any hickups.

Yes you are correct. We are using the SimpleSamlAuth extension. https://www.mediawiki.org/wiki/Extension:SimpleSamlAuth
