### ISSUE TITLE
Uploading/saving a page causes error

### ISSUE THREAD

**Issue by RobertBaruch** [tosher/Mediawiker#126]
Installed package on 2017 Apr 17.

Loading a page works great, but after editing it and saving:

TypeError exception: unorderable types: int() > NoneType()

And, the edit doesn't make it to my wiki.

However, the log (ctrl-`) doesn't have any further message.

**Comment by tosher** [comment]
The message `TypeError exception: unorderable types: int() > NoneType()` is shown at plugin's panel or not?

**Comment by RobertBaruch** [comment]
It's shown in the plugin's panel.

I looked at the wiki's api log, and it only shows queries:

20170417202814,0.045200109481812,104.132.0.88,MwClient/0.8.0.dev1 (https://github.com/mwclient/mwclient),POST,continue=&meta=userinfo&inprop=protection&prop=info&titles=163&format=json&action=query&uiprop=blockinfo%7Chasmsg

**Comment by tosher** [comment]
Are you see only this message in the panel?
If yes - it's on Sublime Text 2 or 3?

**Comment by RobertBaruch** [comment]
Sublime Text 3. The only output in the panel is:

```
TypeError exception: unorderable types: int() > NoneType()
Page [[163]] was successfully published to wiki "Project 54/74".
```

**Comment by RobertBaruch** [comment]
Interestingly, when I edit a page at en.wikipedia.org, it works fine with no exception message in the panel.

**Comment by tosher** [comment]
I think, `pagepath` must be:
```json
"pagepath": "/index.php\\?title="
```

**Comment by RobertBaruch** [comment]
Nope, same problem. Maybe print the stack trace instead of just using status_message? That might help find out what the real problem is...

**Comment by RobertBaruch** [comment]
Here's what I got when I replaced `e` in `status_message` on `mw_commands.py` line 516:

```
Login in with authorization type login..  done
TypeError exception: Traceback (most recent call last):
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "./python3.3/http/client.py", line 1147, in getresponse
  File "./python3.3/http/client.py", line 358, in begin
  File "./python3.3/http/client.py", line 328, in _read_status
http.client.BadStatusLine: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/util/retry.py", line 261, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "./python3.3/http/client.py", line 1147, in getresponse
  File "./python3.3/http/client.py", line 358, in begin
  File "./python3.3/http/client.py", line 328, in _read_status
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/Mediawiker/lib/mwclient/client.py", line 349, in raw_call
    stream = self.connection.post(fullurl, data=data, files=files, headers=headers, **self.requests)
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/requests/all/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/Mediawiker/mwcommands/mw_utils.py", line 514, in save_page
    page.save(text, summary=summary.strip(), minor=mark_as_minor)
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/Mediawiker/lib/mwclient/page.py", line 219, in save
    result = do_edit()
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/Mediawiker/lib/mwclient/page.py", line 214, in do_edit
    **data)
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/Mediawiker/lib/mwclient/client.py", line 275, in api
    info = self.raw_api(action, **kwargs)
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/Mediawiker/lib/mwclient/client.py", line 386, in raw_api
    res = self.raw_call('api', data, retry_on_error=retry_on_error)
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/Mediawiker/lib/mwclient/client.py", line 375, in raw_call
    sleeper.sleep()
  File "/usr/local/google/home/robertbaruch/.config/sublime-text-3/Packages/Mediawiker/lib/mwclient/sleep.py", line 44, in sleep
    if self.retries > self.max_retries:
TypeError: unorderable types: int() > NoneType()

Page [[163]] was successfully published to wiki "Project 54/74".
```

**Comment by tosher** [comment]
Try to change None-values to default:
```python
                connection = mwclient.Site(
                    host=site['hosturl'],
                    path=site['path'],
                    retry_timeout=30,
                    max_retries=25,
                    requests=self.get_requests_config(name)
```
in mw_utils.py:782

**Comment by RobertBaruch** [comment]
Ah, I suspect I'm behind a proxy. I'll need to dig up the proxy settings.

**Comment by RobertBaruch** [comment]
I take that back -- it can't be the proxy settings, since I am able to retrieve pages from my wiki, and edit pages on English Wikipedia... Can you suggest a modification to the code that will display the URL that is being generated?

**Comment by tosher** [comment]
It's just an url to api.php, joined from settings params, as in original library:
https://github.com/mwclient/mwclient/wiki/Site

**Comment by RobertBaruch** [comment]
OK, closing this again. I was able to use Wireshark to see the transactions, and found that I'm getting a 502 Bad Gateway (nginx) from the wiki. I think this is a misconfiguration in nginx, php-fpm, or both. I'll file a ticket with my hosting provider.
