### ISSUE TITLE
Chrome cookie auth issue

### ISSUE THREAD

**Issue by LunarTwilight** [tosher/Mediawiker#163]
When trying to login to fandom.com wiki, using cookie login (using chrome), this error is thrown:

```
  >>> Traceback (most recent call last):
  >>>   File "C:\Users\retracted\AppData\Roaming\Sublime Text 3\Packages\Mediawiker\mwcommands\mw_utils.py", line 762, in get_connect
  >>>     cj = self.get_cookies(name=name) if site['authorization_type'] == self.AUTH_TYPE_COOKIES else None
  >>>   File "C:\Users\retracted\AppData\Roaming\Sublime Text 3\Packages\Mediawiker\mwcommands\mw_utils.py", line 897, in get_cookies
  >>>     return browser_cookie3.chrome(cookie_files=cookie_files, domain_name=site['host'])
  >>>   File "C:\Users\retracted\AppData\Roaming\Sublime Text 3\Packages\Mediawiker\lib\browser_cookie3\__init__.py", line 435, in chrome
  >>>     return Chrome(cookie_files, domain_name).load()
  >>>   File "C:\Users\retracted\AppData\Roaming\Sublime Text 3\Packages\Mediawiker\lib\browser_cookie3\__init__.py", line 250, in load
  >>>     for cookie in self.get_cookies():
  >>>   File "C:\Users\retracted\AppData\Roaming\Sublime Text 3\Packages\Mediawiker\lib\browser_cookie3\__init__.py", line 303, in get_cookies
  >>>     cur.execute(self.SQLREQ_DOMAIN, ('%%%s' % self.domain_name_tld,))
  >>> sqlite3.OperationalError: no such column: secure
  ```

which causes the request to not be authed, and for the saving of the page to abort.

**Comment by tosher** [comment]
Thank you! In last Chrome version this column was renamed, i'll update the library.

**Comment by tosher** [comment]
Please, try the new version:
https://github.com/tosher/Mediawiker/releases/tag/v3.6.3

**Comment by LunarTwilight** [comment]
same error, different stack trace:
```
  >>> Traceback (most recent call last):
  >>>   File "C:\Users\retracted\AppData\Roaming\Sublime Text 3\Packages\Mediawiker\mwcommands\mw_utils.py", line 762, in get_connect
  >>>     site = self.get_site(name)
  >>>   File "C:\Users\retracted\AppData\Roaming\Sublime Text 3\Packages\Mediawiker\mwcommands\mw_utils.py", line 897, in get_cookies
  >>>   File "C:\Users\retracted\AppData\Roaming\Sublime Text 3\Packages\Mediawiker\lib\browser_cookie3\__init__.py", line 435, in chrome
  >>>     # epoch_start = datetime.datetime(1601, 1, 1)
  >>>   File "C:\Users\retracted\AppData\Roaming\Sublime Text 3\Packages\Mediawiker\lib\browser_cookie3\__init__.py", line 250, in load
  >>>     ]
  >>>   File "C:\Users\retracted\AppData\Roaming\Sublime Text 3\Packages\Mediawiker\lib\browser_cookie3\__init__.py", line 303, in get_cookies
  >>>     break
  >>> sqlite3.OperationalError: no such column: secure
```

**Comment by tosher** [comment]
Sublime Text require restart after this upgrade

**Comment by LunarTwilight** [comment]
Yeah apparently even through I didn't have sublime text open before, it still needed a restart before it worked, and now its working for me, thanks for the fix

**Comment by tosher** [comment]
Yep, upgrade process starting after ST starts, after that needs restart :)
