### ISSUE TITLE
[Errno 11004] getaddrinfo failed

### ISSUE THREAD

**Issue by TomBethoule** [tosher/Mediawiker#44]
I have this error when open, save , ... file wiki.

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 356, in run_
  File ".\mediawiker.py", line 179, in run
  File ".\mwutils.py", line 215, in get_connect
  File ".\mwclient\client.py", line 115, in __init__
    self.site_init()
  File ".\mwclient\client.py", line 122, in site_init
    meta = self.api('query', meta='siteinfo|userinfo', siprop='general|namespaces', uiprop='groups|rights')
  File ".\mwclient\client.py", line 185, in api
    info = self.raw_api(action, **kwargs)
  File ".\mwclient\client.py", line 285, in raw_api
    json_data = self.raw_call('api', data).read()
  File ".\mwclient\client.py", line 254, in raw_call
    stream = self.connection.post(self.host, url, data=data, headers=headers)
  File ".\mwclient\httpmw.py", line 288, in post
    return self.find_connection(host).post(host, path, headers, data)
  File ".\mwclient\httpmw.py", line 280, in find_connection
    conn = cls(host, self)
  File ".\mwclient\httpmw.py", line 107, in __init__
    self._conn.connect()
  File ".\httplib.py", line 716, in connect
  File ".\socket.py", line 500, in create_connection
socket.gaierror: [Errno 11004] getaddrinfo failed

**Comment by tosher** [comment]
No connection to wiki host - incorrect address or something else..

**Comment by TomBethoule** [comment]
It's Perfect, thank you Tosher
