### ISSUE TITLE
Version 3.0.0 does not start

### ISSUE THREAD

**Issue by nigobo** [tosher/Mediawiker#52]
```
reloading plugin Mediawiker.mediawiker
Traceback (most recent call last):
  File "/Users/jjaco/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/jjaco/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mediawiker.py", line 21, in <module>
    from . import mwutils as mw
  File "/Users/jjaco/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwutils.py", line 12, in <module>
    import requests
ImportError: No module named 'requests'
reloading plugin Mediawiker.mwsetup
Traceback (most recent call last):
  File "/Users/jjaco/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/jjaco/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwsetup.py", line 9, in <module>
    from . import mwutils as mw
  File "/Users/jjaco/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwutils.py", line 12, in <module>
    import requests
ImportError: No module named 'requests'
reloading plugin Mediawiker.mwutils
Traceback (most recent call last):
  File "/Users/jjaco/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/jjaco/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwutils.py", line 12, in <module>
    import requests
ImportError: No module named 'requests'
```

Thanks for an awesome extension for Sublime. I use it every day.

I cant get the new version of Mediawiker to start. I have tried to reinstall the package and when I look in the console I get the above message. Do I have to install anything more with the new version of Mediawiker?

Any ideas?

**Comment by tosher** [comment]
Must works after second restart of Sublime text.
**requests** - must be installed by Package Control as a dependency module of plugin.

If not, please tell me the Sublime version and OS.

**Comment by tosher** [comment]
Ohhh... sorry.. i'm not set the dependancies for MacOS :(
Will fix it today.

**Comment by tosher** [comment]
Already fixed by [smanolloff](https://github.com/smanolloff)
in https://github.com/tosher/Mediawiker/pull/53

Please try to update plugin.

**Comment by nigobo** [comment]
Hi! It works great again!

Thanks a bunch!

**Comment by tosher** [comment]
Thank you for notice and interest :)
