### ISSUE TITLE
TypeError trying preview: unexpected keyword 'disableeditsection'

### ISSUE THREAD

**Issue by Silberling** [tosher/Mediawiker#63]
Traceback (most recent call last):
	  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 568, in run_
	    return self.run(edit, **args)
	  File "C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\Mediawiker\mediawiker.py", line 1371, in run
	    html = sitecon.parse(text=text, title=mw.get_title(), disableeditsection=True).get('text', {}).get('*', '')
	TypeError: parse() got an unexpected keyword argument 'disableeditsection'

**Comment by tosher** [comment]
It's already *fixed* - please restart or update the plugin.
