### ISSUE TITLE
Connection failed for ('https', 'mywiki'): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550)

### ISSUE THREAD

**Issue by rabin-io** [tosher/Mediawiker#71]
This seems to be the same as issue #54 , 
I have self-sign sertificate for my wiki, and so the verification fails. 
I'm not complete sure, but I think it started just after the last update (3.0.9), 

Adding `self.connection.verify = False` to the file `mwclient/client.py` right after `self.connection = requests.Session()` seems to bypass the problem.

```
        # Setup connection
        if pool is None:
            self.connection = requests.Session()
            self.connection.verify = False
            # self.connection.verify = do_ssl_cert_verify
            # self.connection.proxies = proxies
            self.connection.auth = self.httpauth
            self.connection.headers['User-Agent'] = 'MwClient/' + __ver__ + ' (https://github.com/mwclient/mwclient)'
            if clients_useragent:
                self.connection.headers['User-Agent'] = clients_useragent + ' - ' + self.connection.headers['User-Agent']
        else:
            self.connection = pool
```

1. Please note that I do have the option `"is_ssl_cert_verify": false,` in my configuration.
2. I get 2 pop-up message when trying to open a wiki page.

`________________________________________`

**My Console dump**

```
Traceback (most recent call last):
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 544, in urlopen body=body, headers=headers)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 341, in _make_request self._validate_conn(conn)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn conn.connect()
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connection.py", line 238, in connect ssl_version=resolved_ssl_version)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket return context.wrap_socket(sock, server_hostname=server_hostname)
  File "./ssl.py", line 245, in wrap_socket
  File "./ssl.py", line 345, in __init__
  File "./ssl.py", line 341, in __init__
  File "./ssl.py", line 548, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/adapters.py", line 370, in send timeout=timeout
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 574, in urlopen raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwutils.py", line 285, in get_site sitecon = mwclient.Site(host=self.host, path=self.path, verify=self.is_ssl_cert_verify, proxies=self.proxies)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 118, in __init__ self.site_init()
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 126, in site_init siprop='general|namespaces|namespacealiases', uiprop='groups|rights', retry_on_error=False)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 221, in api info = self.raw_api(action, **kwargs)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 326, in raw_api res = self.raw_call('api', data, retry_on_error=retry_on_error)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 294, in raw_call stream = self.connection.post(fullurl, data=data, files=files, headers=headers, **self.requests)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 508, in post return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 465, in request resp = self.send(prep, **send_kwargs)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 573, in send r = adapter.send(request, **kwargs)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/adapters.py", line 431, in send raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text_3_build_3103/sublime_plugin.py", line 568, in run_ return self.run(edit, **args)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mediawiker.py", line 210, in run sitecon = mw.get_connect(password)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwutils.py", line 146, in get_connect return mwcon.get_site(password)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwutils.py", line 296, in get_site raise Exception('HTTP connection failed: %s' % e) Exception: HTTP connection failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550) Traceback (most recent call last):
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 544, in urlopen body=body, headers=headers)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 341, in _make_request self._validate_conn(conn)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn conn.connect()
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connection.py", line 238, in connect ssl_version=resolved_ssl_version)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket return context.wrap_socket(sock, server_hostname=server_hostname)
  File "./ssl.py", line 245, in wrap_socket 
  File "./ssl.py", line 345, in __init__
  File "./ssl.py", line 341, in __init__
  File "./ssl.py", line 548, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/adapters.py", line 370, in send timeout=timeout
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 574, in urlopen raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwutils.py", line 285, in get_site sitecon = mwclient.Site(host=self.host, path=self.path, verify=self.is_ssl_cert_verify, proxies=self.proxies)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 118, in __init__ self.site_init()
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 126, in site_init siprop='general|namespaces|namespacealiases', uiprop='groups|rights', retry_on_error=False)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 221, in api info = self.raw_api(action, **kwargs)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 326, in raw_api res = self.raw_call('api', data, retry_on_error=retry_on_error)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 294, in raw_call stream = self.connection.post(fullurl, data=data, files=files, headers=headers, **self.requests)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 508, in post return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 465, in request resp = self.send(prep, **send_kwargs)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 573, in send r = adapter.send(request, **kwargs)
  File "/home/rabin/.config/sublime-text-3/Packages/requests/all/requests/adapters.py", line 431, in send raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mediawiker.py", line 72, in on_done panel_passwd.get_password()
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwutils.py", line 406, in get_password self.on_done(password)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwutils.py", line 421, in on_done self.command_run(password)  # defined in executor
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mediawiker.py", line 91, in command_run sitecon = mw.get_connect(password)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwutils.py", line 146, in get_connect return mwcon.get_site(password)
  File "/home/rabin/.config/sublime-text-3/Packages/Mediawiker/mwutils.py", line 296, in get_site raise Exception('HTTP connection failed: %s' % e) Exception: HTTP connection failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550)

```

**Comment by tosher** [comment]
Oh, yes, it's my fault. Will fix it soon..

**Comment by tosher** [comment]
Please, try to update the plugin and check.

**Comment by rabin-io** [comment]
Thanks , working again.
