### ISSUE TITLE
No connection to the Russian Wikipedia

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#86]
### Summary

No connection in Russian Wikipedia

### Steps to reproduce

<kbd>Ctrl+Shift+P</kbd> → `Mediawiker: Open page` → I write and select any page → stack trace:

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ru.wikipedia.org
Traceback (most recent call last):
  File "E:\Sublime Text 3\Data\Packages\Mediawiker\mwcommands\mw_utils.py", line 490, in get_site
    sitecon = mwclient.Site(host=self.host, path=self.path, requests={'verify': self.is_ssl_cert_verify, 'proxies': self.proxies})
  File "E:\Sublime Text 3\Data\Packages\Mediawiker\mwclient\client.py", line 118, in __init__
    self.site_init()
  File "E:\Sublime Text 3\Data\Packages\Mediawiker\mwclient\client.py", line 126, in site_init
    siprop='general|namespaces|namespacealiases', uiprop='groups|rights', retry_on_error=False)
  File "E:\Sublime Text 3\Data\Packages\Mediawiker\mwclient\client.py", line 221, in api
    info = self.raw_api(action, **kwargs)
  File "E:\Sublime Text 3\Data\Packages\Mediawiker\mwclient\client.py", line 326, in raw_api
    res = self.raw_call('api', data, retry_on_error=retry_on_error)
  File "E:\Sublime Text 3\Data\Packages\Mediawiker\mwclient\client.py", line 302, in raw_call
    stream.raise_for_status()
  File "E:\SUBLIM~1\Data\Packages\requests\all\requests\models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Insecure Request Forbidden - use HTTPS - https://lists.wikimedia.org/pipermail/mediawiki-api-announce/2016-May/000110.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "E:\Sublime Text 3\Data\Packages\Mediawiker\mediawiker.py", line 55, in run
    sitecon = mw.get_connect(password)
  File "E:\Sublime Text 3\Data\Packages\Mediawiker\mwcommands\mw_utils.py", line 147, in get_connect
    return mwcon.get_site(password)
  File "E:\Sublime Text 3\Data\Packages\Mediawiker\mwcommands\mw_utils.py", line 497, in get_site
    sublime.message_dialog('HTTP connection failed: %s' % e[1])
TypeError: 'HTTPError' object does not support indexing
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ru.wikipedia.org
Mediawiker exception: 'HTTPError' object does not support indexing
```

### Possible cause of the problem

HTTPS. Link of traceback: <https://lists.wikimedia.org/pipermail/mediawiki-api-announce/2016-May/000110.html>. In my `Medaiwiker `→ `Settings - User` file I replace `"host": "ru.wikipedia.org"` → `"host": "https://ru.wikipedia.org"`, but I don' still could not open any wiki-page.

![Https](http://i.imgur.com/NjU3ddI.png)

### Environment

* Operating system and version:  
      [√] Windows 10 Education
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3114

**Comment by tosher** [comment]
Don't change the address, but use `"https": true` param.
