### ISSUE TITLE
Failure to work: HTTPS now required 

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#87]
Howdy, haven't used mediawiker in a couple months and tried to use it today. MediaWiki changed their API last month to require HTTPS. Does Mediawiker do so?

https://lists.wikimedia.org/pipermail/mediawiki-api-announce/2016-May/000110.html

```
Traceback (most recent call last):
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 490, in get_site
    sitecon = mwclient.Site(host=self.host, path=self.path, requests={'verify': self.is_ssl_cert_verify, 'proxies': self.proxies})
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/client.py", line 118, in __init__
    self.site_init()
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/client.py", line 126, in site_init
    siprop='general|namespaces|namespacealiases', uiprop='groups|rights', retry_on_error=False)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/client.py", line 221, in api
    info = self.raw_api(action, **kwargs)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/client.py", line 326, in raw_api
    res = self.raw_call('api', data, retry_on_error=retry_on_error)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/client.py", line 302, in raw_call
    stream.raise_for_status()
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Insecure Request Forbidden - use HTTPS - https://lists.wikimedia.org/pipermail/mediawiki-api-announce/2016-May/000110.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mediawiker.py", line 55, in run
    sitecon = mw.get_connect(password)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 147, in get_connect
    return mwcon.get_site(password)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 497, in get_site
    sublime.message_dialog('HTTP connection failed: %s' % e[1])
TypeError: 'HTTPError' object does not support indexing
Mediawiker exception: 'HTTPError' object does not support indexing
```

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/issues/86

**Comment by reagle** [comment]
Okay, I saw the fix in #86 but you should probably update the default configuration file to have `"https": true`

```
    "mediawiki_site":
    {
        "English wikipedia": { "host": "en.wikipedia.org", "path": "/w/", "pagepath": "/wiki/", "username": "", "password": "", "domain": "", "https": true, },
        "Russian wikipedia": { "host": "ru.wikipedia.org", "path": "/w/", "pagepath": "/wiki/", "username": "", "password": "", "domain": "", "https": true, },
        "Mediawiki": { "host": "www.mediawiki.org", "path": "/w/", "pagepath": "/wiki/", "username": "", "password": "", "domain": "", "https": true, }
    },
```

**Comment by danmichaelo** [comment]
Perhaps even make https default?

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.1.8.final
