### ISSUE TITLE
«Page preview» don't work

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#89]
I open via Mediawiker any Wikipedia any page, for example, «Кошка» — <https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%88%D0%BA%D0%B0>. <kbd>Alt+F1</kbd> → `Page Preview`. Page not previewed.

```
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "E:\Sublime Text 3\Data\Packages\Mediawiker\mwcommands\mw_preview_page.py", line 63, in run
    html = sitecon.parse(text=text, title=mw.get_title(), disableeditsection=True).get('text', {}).get('*', '')
TypeError: parse() got an unexpected keyword argument 'disableeditsection'

```

Thanks.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.1.10
