### ISSUE TITLE
Auto completion does not work

### ISSUE THREAD

**Issue by johnsidi** [tosher/Mediawiker#95]
I installed MediaWiker 3 hours ago. I have created successfully a connection with my local MediaWiki wiki and everything seems to work fine except the auto completion feature. 

I get the following message on the Console:

Traceback (most recent call last):
  File "/Users/IS/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/listing.py", line 47, in __next__
    item = six.next(self._iter)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/Users/IS/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mediawiker.py", line 247, in on_query_completions
    for p in pages:
  File "/Users/IS/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/listing.py", line 168, in __next__
    info = super(GeneratorList, self).__next__(full=True)
  File "/Users/IS/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/listing.py", line 65, in __next__
    return self.__next__(full=full)
TypeError: __next__() got an unexpected keyword argument 'full'

Any help is greatly appreciated.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.1.13

Please, try the new version.

**Comment by johnsidi** [comment]
Thank you very much, now it works!
