### ISSUE TITLE
Can’t open articles due to SSL error - even when SSL is turned off

### ISSUE THREAD

**Issue by jandahl** [tosher/Mediawiker#97]
I am currently having issues with SSL while connecting to our mediawiki server - even though I have explicitly disabled SSL in my mediawiker settings.

     Connection failed for ('https', 'mediawikiserver.tekdom.local'): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

Having not recently used MediaWiker, it's hard to pin down when this stopped working.

         "mediawiki_site":
         {
             "Teracom IT Wiki":
             {
                 "domain": "",
                 "host": "mediawikiserver.tekdom.local",
                 "https": "false",
                 "pagepath": "/mediawiki/index.php/",
                 "password": "p4ssw0rd",
                 "path": "/mediawiki/",
                 "username": "username"
             }
         },
         "mediawiki_site_active": "Teracom IT Wiki"

Console output:

         Exception: HTTP connection failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
         Mediawiker exception: HTTP connection failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
         Error loading scope:source.tsx: Unable to find syntax file for scope source.tsx in Packages/MarkdownEditing/Markdown.tmLanguage
         Error loading scope:source.scss: Unable to find syntax file for scope source.scss in Packages/MarkdownEditing/Markdown.tmLanguage
         Error loading scope:source.coffee: Unable to find syntax file for scope source.coffee in Packages/MarkdownEditing/Markdown.tmLanguage
         Error loading scope:source.less: Unable to find syntax file for scope source.less in Packages/MarkdownEditing/Markdown.tmLanguage
         Error loading scope:source.scheme: Unable to find syntax file for scope source.scheme in Packages/MarkdownEditing/Markdown.tmLanguage
         Error loading scope:source.sass: Unable to find syntax file for scope source.sass in Packages/MarkdownEditing/Markdown.tmLanguage
         Error loading scope:source.ts: Unable to find syntax file for scope source.ts in Packages/MarkdownEditing/Markdown.tmLanguage
         rule scope:source.scala#xml-comments has a scope name, but is unreachable, so the name will never be used
         Traceback (most recent call last):
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
             body=body, headers=headers)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
             self._validate_conn(conn)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
             conn.connect()
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/packages/urllib3/connection.py", line 238, in connect
             ssl_version=resolved_ssl_version)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
             return context.wrap_socket(sock, server_hostname=server_hostname)
           File "./python3.3/ssl.py", line 246, in wrap_socket
           File "./python3.3/ssl.py", line 350, in __init__
           File "./python3.3/ssl.py", line 346, in __init__
           File "./python3.3/ssl.py", line 553, in do_handshake
         ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

         During handling of the above exception, another exception occurred:

         Traceback (most recent call last):
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/adapters.py", line 370, in send
             timeout=timeout
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
             raise SSLError(e)
         requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

         During handling of the above exception, another exception occurred:

         Traceback (most recent call last):
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 545, in get_site
             sitecon = mwclient.Site(host=self.host, path=self.path, requests={'verify': self.is_ssl_cert_verify, 'proxies': self.proxies})
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/client.py", line 127, in __init__
             self.site_init()
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/client.py", line 148, in site_init
             siprop='general|namespaces|namespacealiases', uiprop='groups|rights', retry_on_error=False)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/client.py", line 269, in api
             info = self.raw_api(action, **kwargs)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/client.py", line 379, in raw_api
             res = self.raw_call('api', data, retry_on_error=retry_on_error)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwclient/client.py", line 342, in raw_call
             stream = self.connection.post(fullurl, data=data, files=files, headers=headers, **self.requests)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/sessions.py", line 508, in post
             return self.request('POST', url, data=data, json=json, **kwargs)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/sessions.py", line 465, in request
             resp = self.send(prep, **send_kwargs)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/sessions.py", line 573, in send
             r = adapter.send(request, **kwargs)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/adapters.py", line 431, in send
             raise SSLError(e, request=request)
         requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

         During handling of the above exception, another exception occurred:

         Traceback (most recent call last):
           File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
             return self.run(edit, **args)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mediawiker.py", line 55, in run
             sitecon = mw.get_connect(password)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 149, in get_connect
             return mwcon.get_site(password)
           File "/Users/jan/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 556, in get_site
             raise Exception('HTTP connection failed: %s' % e)
         Exception: HTTP connection failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
         Mediawiker exception: HTTP connection failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

**Comment by rabin-io** [comment]
try setting `is_ssl_cert_verify` to `false` (put it under "Teracom IT Wiki")

**Comment by tosher** [comment]
Yep :)

**Comment by jandahl** [comment]
Thanks, fixed it!

Also, turns out that I had put in `https` as a var instead of a boolean, so that was also wrong

             "https": "false",

should be 

             "https": false,
